"""Ollama API client with vision model support."""

import base64
from pathlib import Path

from ollama import Client


def encode_image_base64(image_path: Path) -> str:
    """Encode an image to base64.

    Args:
        image_path: Path to the image.

    Returns:
        The base64 encoded image.
    """
    with open(image_path, "rb") as f:
        return base64.b64encode(f.read()).decode("utf-8")


def describe_image(
    image_path: Path,
    model: str,
    system_prompt: str,
    temperature: float = 0.7,
    ollama_host: str | None = None,
) -> str:
    """Generate a description of an image via Ollama.

    Args:
        image_path: Path to the image to describe.
        model: Name of the Ollama model to use.
        system_prompt: System prompt to guide the description.
        temperature: Temperature for generation.
        ollama_host: Ollama server URL (optional).

    Returns:
        The description generated by the model.

    Raises:
        ollama.ResponseError: On Ollama API error.
    """
    image_data = encode_image_base64(image_path)

    client = Client(host=ollama_host) if ollama_host else Client()

    response = client.chat(
        model=model,
        messages=[
            {
                "role": "user",
                "content": system_prompt,
                "images": [image_data],
            }
        ],
        options={"temperature": temperature},
    )

    return response["message"]["content"]
